### ISSUE TITLE
Use Promises for the clean feature

### ISSUE THREAD

**Issue by ghost** [kenzanlabs/pipeline-handyman#23]
The `clean` feature documented [here](https://github.com/kenzanlabs/pipeline-handyman#clean) might return a Promise instead of requiring a callback function, i.e.

```
var handyman = require('pipeline-handyman');

handyman.clean(['.dest/']).then(() => {
  // do something
});
```

and also handle when things go wrong.

**Comment by obuckley-kenzan** [comment]
good suggestion, thanks!
