### ISSUE TITLE
Add clean() method

### ISSUE THREAD

**Issue by jansensan** [kenzanlabs/pipeline-handyman#9]
`handyman` could benefit from the addition of a `clean()` method which would be a wrapper around the [`del`](https://www.npmjs.com/package/del) Node module.

**Comment by obuckley-kenzan** [comment]
I like it :+1:

**Comment by jansensan** [comment]
@obuckley-kenzan Forgot to reply to your question: a glob is passed, so a file path, a directory path or a glob are acceptable. It will also be possible to use it as a pipe.

**Comment by obuckley-kenzan** [comment]
nice!
